[project]
name = "flashcards-py"
version = "0.1.0"
description = "A Python CLI studying app designed for simplicity and speed."
readme = "README.md"
authors = [
    { name = "garden-yardripper", email = "gardenyardripper@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F"]
